const cfg=window.APP_CONFIG;
const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={profile:localStorage.getItem("couple_profile"),settings:{id:1,partner_one:"진성",partner_two:"성은"},shopping:[],trips:[],records:[],schedules:[],scheduleCategories:[],expenseCategories:[],scheduleFilter:"전체",categoryMode:null,calendarItem:null,calendarButton:null,scheduleViewMode:"calendar",calendarCursor:new Date(),selectedCalendarDate:null,moneyViewMode:"list",moneySummaryMonth:iso().slice(0,7)};
const els={profileScreen:$("#profileScreen"),app:$("#app"),toast:$("#toast"),oneName:$("#profileOneName"),twoName:$("#profileTwoName"),today:$("#todayText"),pageTitle:$("#pageTitle"),welcome:$("#welcomeName"),shoppingCount:$("#shoppingCount"),tripCount:$("#tripCount"),scheduleCount:$("#scheduleCount"),homeExpenseTotal:$("#homeExpenseTotal"),homeSchedules:$("#homeSchedules"),homeTrips:$("#homeTrips"),shoppingList:$("#shoppingList"),tripList:$("#tripList"),scheduleList:$("#scheduleList"),pastScheduleList:$("#pastScheduleList"),scheduleFilters:$("#scheduleFilters"),scheduleCalendar:$("#scheduleCalendar"),calendarDayEvents:$("#calendarDayEvents"),currentProfile:$("#currentProfileText"),moneyWriter:$("#moneyWriter"),moneyList:$("#moneyList"),monthExpenseTotal:$("#monthExpenseTotal"),monthExpenseCount:$("#monthExpenseCount"),moneyCategorySummary:$("#moneyCategorySummary"),moneyWriterSummary:$("#moneyWriterSummary")};
function toast(msg){els.toast.textContent=msg;els.toast.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>els.toast.hidden=true,2500)}
function iso(d=new Date()){return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function fmtDate(v){if(!v)return "";const [y,m,d]=String(v).slice(0,10).split("-").map(Number);const day=["일","월","화","수","목","금","토"][new Date(y,m-1,d).getDay()];return `${y}년${m}월${d}일(${day})`}
function money(v){return `${Number(v||0).toLocaleString("ko-KR")}원`}
function currentName(){return state.profile==="one"?state.settings.partner_one:state.settings.partner_two}
function escapeICS(v=""){return String(v).replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function localCalendarKey(item){return `calendar_saved_${item.source}_${item.id}`}
function isCalendarSaved(item){return localStorage.getItem(localCalendarKey(item))==="1"}
function ymdCompact(v){return (v||iso()).replaceAll("-","")}
function dtCompact(date,time){return `${ymdCompact(date)}T${(time||"09:00").replace(":","")}00`}

async function loadAll(){
  const qs=await Promise.all([
    sb.from("couple_settings").select("*").eq("id",1).maybeSingle(),sb.from("shopping_items").select("*").order("created_at",{ascending:false}),sb.from("travel_plans").select("*").order("start_date",{ascending:true}),sb.from("couple_items").select("*").order("created_at",{ascending:false}),sb.from("schedule_events").select("*").order("start_date",{ascending:true}),sb.from("schedule_categories").select("*").order("sort_order"),sb.from("expense_categories").select("*").order("sort_order")
  ]);
  if(qs[0].data)state.settings={...state.settings,...qs[0].data};state.shopping=qs[1].data||[];state.trips=qs[2].data||[];state.records=qs[3].data||[];state.schedules=qs[4].data||[];state.scheduleCategories=qs[5].data||[];state.expenseCategories=qs[6].data||[];
  if(qs.some(q=>q.error))toast("일부 데이터를 불러오지 못했습니다. setup_v7.sql 실행 여부를 확인하세요.");renderAll();
}
function openApp(){els.profileScreen.hidden=true;els.app.hidden=false;loadAll().then(handleLaunchRoute)}
function chooseProfile(profile){state.profile=profile;localStorage.setItem("couple_profile",profile);openApp()}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$("#"+view+"View").classList.add("active");$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));els.pageTitle.textContent={home:"홈",shopping:"장보기",travel:"여행",schedule:"일정",money:"가계부",settings:"설정"}[view];if(view==="money")setTimeout(()=>$("#moneyAmount")?.focus(),120)}
function unifiedSchedules(){
  const normal=state.schedules.map(x=>({...x,source:"schedule",sourceLabel:"일정"}));
  const trips=state.trips.filter(x=>x.start_date).map(x=>({id:x.id,title:`✈ ${x.title}`,start_date:x.start_date,end_date:x.end_date||x.start_date,all_day:true,start_time:null,end_time:null,category:"여행",location:null,memo:x.memo,writer:x.writer,target_person:"모두",source:"travel",sourceLabel:"여행"}));
  return [...normal,...trips].sort((a,b)=>(a.start_date||"").localeCompare(b.start_date||""));
}
function renderAll(){
  els.oneName.textContent=state.settings.partner_one;els.twoName.textContent=state.settings.partner_two;els.welcome.textContent=`${currentName()}님, 안녕하세요`;els.currentProfile.textContent=`이 기기 사용자: ${currentName()}`;$("#partnerOneInput").value=state.settings.partner_one;$("#partnerTwoInput").value=state.settings.partner_two;
  els.moneyWriter.innerHTML="";[state.settings.partner_one,state.settings.partner_two].forEach(n=>els.moneyWriter.add(new Option(n,n)));
  fillScheduleTargetSelect();
  fillCategorySelects();
  const now=new Date(), monthlyExpenses=state.records.filter(x=>{if(x.category!=="가계부"||x.amount==null)return false;const d=x.event_date?new Date(x.event_date+"T00:00:00"):new Date(x.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});const monthlyTotal=monthlyExpenses.reduce((sum,x)=>sum+Number(x.amount||0),0);const all=unifiedSchedules();
  els.shoppingCount.textContent=state.shopping.filter(x=>!x.completed).length;els.tripCount.textContent=state.trips.filter(x=>!x.end_date||x.end_date>=iso()).length;els.scheduleCount.textContent=all.filter(x=>(x.end_date||x.start_date)>=iso()).length;els.homeExpenseTotal.textContent=money(monthlyTotal);els.monthExpenseTotal.textContent=money(monthlyTotal);els.monthExpenseCount.textContent=`${monthlyExpenses.length}건`;
  renderMini(els.homeSchedules,all.filter(x=>(x.end_date||x.start_date)>=iso()).slice(0,4).map(x=>({title:x.title,meta:`${fmtDate(x.start_date)} · ${x.category||"미분류"} · ${x.target_person||x.writer||"모두"}`})),"다가오는 일정이 없습니다.");renderMini(els.homeTrips,state.trips.filter(x=>!x.end_date||x.end_date>=iso()).slice(0,3).map(x=>({title:x.title,meta:[fmtDate(x.start_date),fmtDate(x.end_date)].filter(Boolean).join(" ~ ")})),"예정된 여행이 없습니다.");renderShopping();renderTrips();renderSchedules();renderMoney(state.records.filter(x=>x.category==="가계부"&&x.amount!=null));
}
function fillScheduleTargetSelect(selected){const el=$("#scheduleTarget");if(!el)return;const keep=selected||el.value||currentName();el.innerHTML="";[state.settings.partner_one,state.settings.partner_two,"모두"].forEach(n=>el.add(new Option(n,n)));el.value=[...el.options].some(o=>o.value===keep)?keep:currentName()}
function fillCategorySelects(){const sc=$("#scheduleCategory"),mc=$("#moneyCategory");const sv=sc.value,mv=mc.value;sc.innerHTML="";mc.innerHTML="";(state.scheduleCategories.length?state.scheduleCategories:[{name:"미분류"}]).forEach(c=>sc.add(new Option(c.name,c.name)));(state.expenseCategories.length?state.expenseCategories:[{name:"기타"}]).forEach(c=>mc.add(new Option(c.name,c.name)));if([...sc.options].some(o=>o.value===sv))sc.value=sv;if([...mc.options].some(o=>o.value===mv))mc.value=mv;const mf=document.querySelector("#moneyCategoryFilter");if(mf){const keep=mf.value;mf.innerHTML='<option value="all">전체 카테고리</option>';(state.expenseCategories.length?state.expenseCategories:[]).forEach(c=>mf.add(new Option(c.name,c.name)));if([...mf.options].some(o=>o.value===keep))mf.value=keep}}
function renderMini(container,list,emptyText){container.innerHTML="";if(!list.length){container.innerHTML=`<div class="empty">${emptyText}</div>`;return}list.forEach(x=>{const row=document.createElement("div");row.className="list-item";row.innerHTML="<div></div><div><strong></strong><div class='meta'></div></div><div></div>";row.querySelector("strong").textContent=x.title;row.querySelector(".meta").textContent=x.meta||"";container.append(row)})}
async function addShopping(){const item=$("#shopItem").value.trim();if(!item)return toast("살 물건을 입력하세요.");const {error}=await sb.from("shopping_items").insert({item_name:item,quantity:$("#shopQty").value.trim()||null,store:$("#shopStore").value||null,completed:false,writer:currentName()});if(error)return toast("추가하지 못했습니다.");$("#shopItem").value="";$("#shopQty").value="";await loadAll()}
async function toggleShopping(item){await sb.from("shopping_items").update({completed:!item.completed}).eq("id",item.id);await loadAll()}

function editField(label,id,type="text",value="",options=null){
  const wrap=document.createElement("label");wrap.textContent=label;
  let input;
  if(options){input=document.createElement("select");options.forEach(o=>input.add(new Option(o,o)));input.value=value||options[0]||""}
  else if(type==="textarea"){input=document.createElement("textarea");input.rows=4;input.value=value||""}
  else{input=document.createElement("input");input.type=type;input.value=value??""}
  input.id=id;wrap.append(input);return wrap
}
function openEditDialog(type,x){
  state.editing={type,item:x};const form=$("#editFormFields");form.innerHTML="";
  const titleMap={shopping:"장보기 수정",travel:"여행 수정",schedule:"일정 수정",money:"가계부 수정"};
  $("#editDialogTitle").textContent=titleMap[type];
  if(type==="shopping"){
    form.append(editField("물건 이름","editName","text",x.item_name),editField("수량","editQuantity","text",x.quantity||""),editField("구매 장소","editStore","text",x.store||""));
  }else if(type==="travel"){
    form.append(editField("여행 이름 또는 목적지","editName","text",x.title),editField("시작 날짜","editStart","date",x.start_date||""),editField("종료 날짜","editEnd","date",x.end_date||x.start_date||""),editField("여행 메모","editMemo","textarea",x.memo||""));
  }else if(type==="schedule"){
    const cats=(state.scheduleCategories.length?state.scheduleCategories.map(c=>c.name):["미분류"]);if(x.category&&!cats.includes(x.category))cats.push(x.category);
    form.append(editField("일정 제목","editName","text",x.title),editField("시작 날짜","editStart","date",x.start_date||""),editField("종료 날짜","editEnd","date",x.end_date||x.start_date||""),editField("일정 대상","editTarget","select",x.target_person||x.writer||"모두",[state.settings.partner_one,state.settings.partner_two,"모두"]));
    const allWrap=document.createElement("label");allWrap.className="edit-check-line";const all=document.createElement("input");all.type="checkbox";all.id="editAllDay";all.checked=x.all_day!==false;allWrap.append(all,document.createTextNode("하루 종일"));form.append(allWrap);
    const timeRow=document.createElement("div");timeRow.className="grid";timeRow.id="editTimeRow";timeRow.append(editField("시작 시간","editStartTime","time",x.start_time||"09:00"),editField("종료 시간","editEndTime","time",x.end_time||"10:00"));timeRow.hidden=all.checked;form.append(timeRow);
    all.onchange=()=>timeRow.hidden=all.checked;
    form.append(editField("카테고리","editCategory","select",x.category||"미분류",cats),editField("장소","editLocation","text",x.location||""),editField("메모","editMemo","textarea",x.memo||""));
  }else if(type==="money"){
    const cats=(state.expenseCategories.length?state.expenseCategories.map(c=>c.name):["미분류"]);if(x.expense_group&&!cats.includes(x.expense_group))cats.push(x.expense_group);
    const writers=[state.settings.partner_one,state.settings.partner_two];if(x.writer&&!writers.includes(x.writer))writers.push(x.writer);
    form.append(editField("사용처 또는 내용","editName","text",x.content),editField("금액","editAmount","number",x.amount||""),editField("날짜","editDate","date",x.event_date||iso()),editField("카테고리","editCategory","select",x.expense_group||"미분류",cats),editField("작성자","editWriter","select",x.writer||currentName(),writers));
  }
  const start=$("#editStart"),endDate=$("#editEnd");if(start&&endDate)start.onchange=()=>{if(!endDate.value||endDate.value<start.value)endDate.value=start.value};
  $("#editDialog").showModal();setTimeout(()=>$("#editName")?.focus(),80)
}
async function saveEditedItem(){
  const e=state.editing;if(!e)return;const x=e.item;let table,payload;
  const name=$("#editName")?.value.trim();if(!name)return toast(e.type==="money"?"사용처나 내용을 입력하세요.":"이름이나 제목을 입력하세요.");
  if(e.type==="shopping"){
    table="shopping_items";payload={item_name:name,quantity:$("#editQuantity").value.trim()||null,store:$("#editStore").value.trim()||null};
  }else if(e.type==="travel"){
    const start=$("#editStart").value,end=$("#editEnd").value||start;if(start&&end<start)return toast("종료 날짜를 확인하세요.");table="travel_plans";payload={title:name,start_date:start||null,end_date:end||null,memo:$("#editMemo").value.trim()||null};
  }else if(e.type==="schedule"){
    const start=$("#editStart").value,end=$("#editEnd").value||start;if(!start)return toast("시작 날짜를 선택하세요.");if(end<start)return toast("종료 날짜를 확인하세요.");const all=$("#editAllDay").checked;table="schedule_events";payload={title:name,start_date:start,end_date:end,all_day:all,start_time:all?null:$("#editStartTime").value||null,end_time:all?null:$("#editEndTime").value||null,target_person:$("#editTarget").value||"모두",category:$("#editCategory").value||"미분류",location:$("#editLocation").value.trim()||null,memo:$("#editMemo").value.trim()||null};localStorage.removeItem(localCalendarKey({...x,source:"schedule"}));
  }else{
    const amount=Number($("#editAmount").value);if(!amount||amount<=0)return toast("금액을 확인하세요.");table="couple_items";payload={content:name,amount,event_date:$("#editDate").value||iso(),expense_group:$("#editCategory").value||"미분류",writer:$("#editWriter").value||currentName()};
  }
  const {error}=await sb.from(table).update(payload).eq("id",x.id);if(error)return toast("수정하지 못했습니다.");$("#editDialog").close();state.editing=null;await loadAll();toast("수정했습니다.")
}
function editShopping(x){openEditDialog("shopping",x)}
function editTrip(x){openEditDialog("travel",x)}
function editSchedule(x){openEditDialog("schedule",x)}
function editMoney(x){openEditDialog("money",x)}
function editButton(handler){const b=document.createElement("button");b.className="small-button";b.textContent="수정";b.onclick=handler;return b}
async function removeRow(table,id,message="삭제할까요?"){if(!confirm(message))return;await sb.from(table).delete().eq("id",id);await loadAll()}
function renderShopping(){
  const q=(document.querySelector("#shoppingSearch")?.value||"").trim().toLowerCase(),status=document.querySelector("#shoppingStatusFilter")?.value||"all";
  const list=state.shopping.filter(x=>(!q||(x.item_name||"").toLowerCase().includes(q))&&(status==="all"||(status==="open"&&!x.completed)||(status==="done"&&x.completed)));
  els.shoppingList.innerHTML="";if(!list.length){els.shoppingList.innerHTML='<div class="empty">조건에 맞는 장보기 항목이 없습니다.</div>';return}
  list.forEach(x=>{const row=document.createElement("div");row.className=`list-item ${x.completed?"done":""}`;const check=document.createElement("button");check.className="check-button";check.textContent=x.completed?"✓":"";check.onclick=()=>toggleShopping(x);const body=document.createElement("div");body.innerHTML="<strong></strong><div class='meta'></div>";body.querySelector("strong").textContent=x.item_name;body.querySelector(".meta").textContent=[x.quantity,x.store,x.writer].filter(Boolean).join(" · ");const actions=document.createElement("div");actions.className="item-actions";const edit=editButton(()=>editShopping(x));const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("shopping_items",x.id);actions.append(edit,del);row.append(check,body,actions);els.shoppingList.append(row)})
}
async function addTrip(){const title=$("#tripTitle").value.trim();if(!title)return toast("여행 이름이나 목적지를 입력하세요.");const {error}=await sb.from("travel_plans").insert({title,start_date:$("#tripStart").value||null,end_date:$("#tripEnd").value||null,memo:$("#tripMemo").value.trim()||null,writer:currentName()});if(error)return toast("여행 계획을 추가하지 못했습니다.");$("#tripTitle").value="";$("#tripStart").value="";$("#tripEnd").value="";$("#tripMemo").value="";await loadAll()}
function renderTrips(){
  const q=(document.querySelector("#travelSearch")?.value||"").trim().toLowerCase(),status=document.querySelector("#travelStatusFilter")?.value||"all",today=iso();
  const list=state.trips.filter(x=>{const hit=!q||`${x.title||""} ${x.memo||""}`.toLowerCase().includes(q);const st=!x.start_date||x.start_date>today?"upcoming":((x.end_date||x.start_date)>=today?"ongoing":"past");return hit&&(status==="all"||status===st)});
  els.tripList.innerHTML="";if(!list.length){els.tripList.innerHTML='<div class="empty">조건에 맞는 여행 계획이 없습니다.</div>';return}
  list.forEach(x=>{const card=document.createElement("article");card.className="trip-card";const title=document.createElement("strong");title.textContent=x.title;const meta=document.createElement("div");meta.className="meta";meta.textContent=[fmtDate(x.start_date),fmtDate(x.end_date),x.writer].filter(Boolean).join(" ~ ");const memo=document.createElement("p");memo.textContent=x.memo||"메모 없음";const actions=document.createElement("div");actions.className="card-actions";const cal=calendarButton({...x,source:"travel",category:"여행",all_day:true});const edit=editButton(()=>editTrip(x));const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("travel_plans",x.id,"여행 계획을 삭제할까요?");actions.append(cal,edit,del);card.append(title,meta,memo,actions);els.tripList.append(card)})
}
async function addSchedule(){const title=$("#scheduleTitle").value.trim(),start=$("#scheduleStartDate").value,end=$("#scheduleEndDate").value||start;if(!title)return toast("일정 제목을 입력하세요.");if(!start)return toast("시작 날짜를 선택하세요.");if(end<start)return toast("종료 날짜를 확인하세요.");const all=$("#scheduleAllDay").checked;const {error}=await sb.from("schedule_events").insert({title,start_date:start,end_date:end,all_day:all,start_time:all?null:$("#scheduleStartTime").value||null,end_time:all?null:$("#scheduleEndTime").value||null,target_person:$("#scheduleTarget").value||currentName(),category:$("#scheduleCategory").value||"미분류",location:$("#scheduleLocation").value.trim()||null,memo:$("#scheduleMemo").value.trim()||null,writer:currentName()});if(error)return toast("일정을 저장하지 못했습니다.");["#scheduleTitle","#scheduleStartDate","#scheduleEndDate","#scheduleStartTime","#scheduleEndTime","#scheduleLocation","#scheduleMemo"].forEach(s=>$(s).value="");$("#scheduleAllDay").checked=true;$("#scheduleTimeRow").hidden=true;fillScheduleTargetSelect(currentName());await loadAll();closeScheduleForm();toast("일정을 저장했습니다.")}
function scheduleMatches(x,q){return !q||`${x.title||""} ${x.memo||""} ${x.location||""}`.toLowerCase().includes(q)}
function scheduleCategoryMatches(x){return state.scheduleFilter==="전체"||(x.category||"미분류")===state.scheduleFilter}
function scheduleCard(x){
  const card=document.createElement("article");card.className=`schedule-card ${x.source==="travel"?"travel-linked":""}`;
  const top=document.createElement("div");top.className="schedule-card-top";const title=document.createElement("strong");title.textContent=x.title;const badge=document.createElement("span");badge.className="category-badge";badge.textContent=x.category||"미분류";top.append(title,badge);
  const meta=document.createElement("div");meta.className="meta schedule-meta";
  const date=document.createElement("span");date.textContent=dateRangeText(x);meta.append(date);
  const target=x.target_person||x.writer;if(target){const sep=document.createElement("span");sep.textContent=" · ";const targetEl=document.createElement("span");targetEl.className="schedule-target-display";targetEl.textContent=target;meta.append(sep,targetEl)}
  if(x.location){const sep=document.createElement("span");sep.textContent=" · ";const loc=document.createElement("span");loc.textContent=x.location;meta.append(sep,loc)}
  const memo=document.createElement("p");memo.textContent=x.memo||"";
  const actions=document.createElement("div");actions.className="card-actions";actions.append(calendarButton(x));if(x.source==="schedule"){const edit=editButton(()=>editSchedule(x));const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("schedule_events",x.id,"이 일정을 삭제할까요?");actions.append(edit,del)}else{const hint=document.createElement("small");hint.textContent="여행 메뉴와 자동 연결됨";actions.append(hint)}card.append(top,meta,memo,actions);return card
}
function renderScheduleCards(container,list,emptyText){container.innerHTML="";if(!list.length){container.innerHTML=`<div class="empty">${emptyText}</div>`;return}list.forEach(x=>container.append(scheduleCard(x)))}
function renderSchedules(){
  const all=unifiedSchedules(),q=(document.querySelector("#scheduleSearch")?.value||"").trim().toLowerCase(),period=document.querySelector("#scheduleDateFilter")?.value||"future",today=iso();
  els.scheduleFilters.innerHTML="";["전체","여행",...state.scheduleCategories.map(c=>c.name).filter(n=>n!=="여행")].filter((v,i,a)=>a.indexOf(v)===i).forEach(name=>{const b=document.createElement("button");b.className=`chip ${state.scheduleFilter===name?"active":""}`;b.textContent=name;b.onclick=()=>{state.scheduleFilter=name;renderSchedules()};els.scheduleFilters.append(b)});
  const td=new Date(today+"T00:00:00"),weekEnd=new Date(td);weekEnd.setDate(td.getDate()+6-td.getDay()),monthEnd=new Date(td.getFullYear(),td.getMonth()+1,0);const wEnd=iso(weekEnd),mStart=`${today.slice(0,7)}-01`,mEnd=iso(monthEnd);
  const common=x=>scheduleCategoryMatches(x)&&scheduleMatches(x,q),future=all.filter(x=>common(x)&&(x.end_date||x.start_date)>=today).filter(x=>{const sd=x.start_date||"",ed=x.end_date||sd;if(period==="today")return sd<=today&&ed>=today;if(period==="week")return sd<=wEnd&&ed>=today;if(period==="month")return sd<=mEnd&&ed>=mStart;return true});
  const past=all.filter(x=>common(x)&&(x.end_date||x.start_date)<today).sort((a,b)=>(b.end_date||b.start_date).localeCompare(a.end_date||a.start_date));
  renderScheduleCards(els.scheduleList,future,"다가오는 일정이 없습니다.");renderScheduleCards(els.pastScheduleList,past,"지난 일정이 없습니다.");const count=document.querySelector("#pastScheduleCount");if(count)count.textContent=`(${past.length}건)`;renderScheduleCalendar()
}
function placeScheduleForm(){const panel=document.querySelector("#scheduleFormPanel"),list=document.querySelector("#scheduleListSection"),calendar=document.querySelector("#scheduleCalendarSection");if(!panel||!list||!calendar)return;if(state.scheduleViewMode==="list")list.prepend(panel);else calendar.append(panel)}
function showScheduleMode(mode){state.scheduleViewMode=mode;const calendar=mode==="calendar";document.querySelector("#scheduleCalendarSection").hidden=!calendar;document.querySelector("#scheduleListSection").hidden=calendar;document.querySelector("#calendarViewButton").classList.toggle("active",calendar);document.querySelector("#listViewButton").classList.toggle("active",!calendar);localStorage.setItem("schedule_view_mode",mode);placeScheduleForm();if(calendar)renderScheduleCalendar();else renderSchedules()}
function openScheduleForm(date){const panel=document.querySelector("#scheduleFormPanel");fillScheduleTargetSelect(currentName());placeScheduleForm();if(date){document.querySelector("#scheduleStartDate").value=date;document.querySelector("#scheduleEndDate").value=date}panel.hidden=false;requestAnimationFrame(()=>{panel.scrollIntoView({behavior:"smooth",block:"start"});setTimeout(()=>document.querySelector("#scheduleTitle")?.focus(),250)})}
function closeScheduleForm(){const panel=document.querySelector("#scheduleFormPanel");if(panel)panel.hidden=true}
function eventsOnDate(date){return unifiedSchedules().filter(x=>(x.start_date||"")<=date&&(x.end_date||x.start_date||"")>=date)}
function renderScheduleCalendar(){
  if(!els.scheduleCalendar)return;const cursor=state.calendarCursor instanceof Date?state.calendarCursor:new Date();const y=cursor.getFullYear(),m=cursor.getMonth();document.querySelector("#calendarMonthTitle").textContent=`${y}년 ${m+1}월`;
  const first=new Date(y,m,1),gridStart=new Date(y,m,1-first.getDay()),today=iso();els.scheduleCalendar.innerHTML="";
  for(let i=0;i<42;i++){const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);const key=iso(d),events=eventsOnDate(key);const cell=document.createElement("button");cell.type="button";cell.className=`calendar-day ${d.getMonth()!==m?"other-month":""} ${key===today?"today":""} ${key===state.selectedCalendarDate?"selected":""}`;const num=document.createElement("span");num.className="day-number";num.textContent=d.getDate();cell.append(num);events.slice(0,2).forEach(ev=>{const dot=document.createElement("span");dot.className=`calendar-event-dot ${ev.source==="travel"?"travel":""}`;dot.textContent=ev.title;cell.append(dot)});if(events.length>2){const more=document.createElement("span");more.className="calendar-more";more.textContent=`+${events.length-2}개`;cell.append(more)}cell.onclick=()=>{state.selectedCalendarDate=key;if(d.getMonth()!==m){state.calendarCursor=new Date(d.getFullYear(),d.getMonth(),1)}renderScheduleCalendar()};els.scheduleCalendar.append(cell)}
  renderCalendarDayEvents(state.selectedCalendarDate||today)
}
function renderCalendarDayEvents(date){if(!els.calendarDayEvents)return;const events=eventsOnDate(date);els.calendarDayEvents.innerHTML=`<h3 class="calendar-day-title">${fmtDate(date)} 일정</h3>`;if(!events.length){els.calendarDayEvents.innerHTML+='<div class="empty">이 날짜의 일정이 없습니다.</div>';return}events.forEach(x=>{const box=document.createElement("article");box.className="calendar-day-event";const title=document.createElement("strong");title.textContent=x.title;const meta=document.createElement("div");meta.className="meta";meta.textContent=[x.category,dateRangeText(x),x.location,x.target_person||x.writer||"모두"].filter(Boolean).join(" · ");box.append(title,meta);box.onclick=()=>{if(x.source==="schedule")editSchedule(x)};els.calendarDayEvents.append(box)})}
function dateRangeText(x){const d=x.start_date===x.end_date||!x.end_date?fmtDate(x.start_date):`${fmtDate(x.start_date)} ~ ${fmtDate(x.end_date)}`;return x.all_day!==false?d:`${d} ${x.start_time||""}${x.end_time?`~${x.end_time}`:""}`}
function calendarButton(item){const b=document.createElement("button");b.className=isCalendarSaved(item)?"calendar-button saved":"calendar-button";b.textContent=isCalendarSaved(item)?"✓ 저장 완료":"📅 휴대폰 캘린더에 추가";b.onclick=()=>addToDeviceCalendar(item,b);return b}
function calendarDates(item){const start=item.start_date||iso(),end=item.end_date||start;if(item.all_day!==false){const next=new Date(end+"T00:00:00");next.setDate(next.getDate()+1);return `${ymdCompact(start)}/${ymdCompact(iso(next))}`}return `${dtCompact(start,item.start_time||"09:00")}/${dtCompact(end,item.end_time||item.start_time||"10:00")}`}
function googleCalendarUrl(item){return `https://calendar.google.com/calendar/render?${new URLSearchParams({action:"TEMPLATE",text:item.title||"일정",dates:calendarDates(item),details:item.memo||"",location:item.location||"",ctz:"Asia/Seoul"}).toString()}`}
function icsText(item){const start=item.start_date||iso(),end=item.end_date||start;let ds,de;if(item.all_day!==false){const next=new Date(end+"T00:00:00");next.setDate(next.getDate()+1);ds=`DTSTART;VALUE=DATE:${ymdCompact(start)}`;de=`DTEND;VALUE=DATE:${ymdCompact(iso(next))}`}else{ds=`DTSTART;TZID=Asia/Seoul:${dtCompact(start,item.start_time||"09:00")}`;de=`DTEND;TZID=Asia/Seoul:${dtCompact(end,item.end_time||item.start_time||"10:00")}`}return ["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//우리둘//V10//KO","BEGIN:VEVENT",`UID:${item.source||"schedule"}-${item.id||Date.now()}@our-couple-app`,ds,de,`SUMMARY:${escapeICS(item.title||"일정")}`,`DESCRIPTION:${escapeICS(item.memo||"")}`,`LOCATION:${escapeICS(item.location||"")}`,"END:VEVENT","END:VCALENDAR"].join("\r\n")}
function markCalendarSaved(){if(!state.calendarItem)return;localStorage.setItem(localCalendarKey(state.calendarItem),"1");if(state.calendarButton){state.calendarButton.textContent="✓ 저장 완료";state.calendarButton.classList.add("saved")}}
function addToDeviceCalendar(item,button){if(isCalendarSaved(item)&&!confirm("이미 이 휴대폰에서 추가한 일정입니다. 다시 추가하면 중복될 수 있습니다. 다시 추가할까요?"))return;state.calendarItem=item;state.calendarButton=button;document.querySelector("#calendarDialog").showModal()}

function showMoneyMode(mode){
  state.moneyViewMode=mode;
  $("#moneyListSection").hidden=mode!=="list";
  $("#moneySummarySection").hidden=mode!=="summary";
  $("#moneyListViewButton").classList.toggle("active",mode==="list");
  $("#moneySummaryViewButton").classList.toggle("active",mode==="summary");
  if(mode==="summary")renderMoneySummary(state.records.filter(x=>x.category==="가계부"&&x.amount!=null));
}
function setMoneySummaryMonth(offset=0){
  const [y,m]=state.moneySummaryMonth.split("-").map(Number),d=new Date(y,m-1+offset,1);
  state.moneySummaryMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
  const input=$("#moneySummaryMonth");if(input)input.value=state.moneySummaryMonth;
  renderMoneySummary(state.records.filter(x=>x.category==="가계부"&&x.amount!=null));
}
function renderSummaryRows(container,items,total){
  container.innerHTML="";
  if(!items.length){container.innerHTML='<div class="empty">이 달의 지출 내역이 없습니다.</div>';return}
  items.forEach(([name,amount,count])=>{const row=document.createElement("div");row.className="summary-row";const pct=total?Math.round(amount/total*100):0;row.innerHTML=`<div class="summary-row-top"><strong></strong><span>${money(amount)} · ${count}건</span></div><div class="summary-bar"><i style="width:${pct}%"></i></div>`;row.querySelector("strong").textContent=name;container.append(row)});
}
function renderMoneySummary(all){
  const prefix=state.moneySummaryMonth||iso().slice(0,7),list=all.filter(x=>(x.event_date||"").startsWith(prefix));
  const total=list.reduce((sum,x)=>sum+Number(x.amount||0),0);
  $("#moneySummaryTotal").textContent=money(total);$("#moneySummaryCount").textContent=`${list.length}건`;
  const groupBy=key=>{const map=new Map();list.forEach(x=>{const name=x[key]||"미분류",v=map.get(name)||[0,0];map.set(name,[v[0]+Number(x.amount||0),v[1]+1])});return [...map.entries()].map(([name,[amount,count]])=>[name,amount,count]).sort((a,b)=>b[1]-a[1])};
  renderSummaryRows(els.moneyCategorySummary,groupBy("expense_group"),total);renderSummaryRows(els.moneyWriterSummary,groupBy("writer"),total);
}
async function shareDeviceCalendar(){const item=state.calendarItem;if(!item)return;const file=new File([icsText(item)],`${(item.title||"일정").replace(/[\/:*?"<>|]/g,"_")}.ics`,{type:"text/calendar"});try{if(navigator.canShare?.({files:[file]})){await navigator.share({title:item.title||"일정",files:[file]});markCalendarSaved();document.querySelector("#calendarDialog").close();toast("공유 목록에서 삼성 캘린더 또는 기본 캘린더를 선택해 저장하세요.");return}}catch(e){if(e.name==="AbortError")return}const url=URL.createObjectURL(file),a=document.createElement("a");a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);markCalendarSaved();document.querySelector("#calendarDialog").close();toast("기기 제한으로 캘린더 파일을 열었습니다.")}
function openGoogleCalendar(){const item=state.calendarItem;if(!item)return;const opened=window.open(googleCalendarUrl(item),"_blank");if(!opened)location.href=googleCalendarUrl(item);markCalendarSaved();document.querySelector("#calendarDialog").close();toast("Google 캘린더에서 저장을 눌러주세요.")}
async function addMoney(){const amount=Number($("#moneyAmount").value),content=$("#moneyContent").value.trim();if(!amount||amount<=0)return toast("금액을 입력하세요.");if(!content)return toast("사용한 곳이나 내용을 입력하세요.");const {error}=await sb.from("couple_items").insert({content,category:"가계부",writer:els.moneyWriter.value,completed:false,event_date:$("#moneyDate").value||iso(),amount,expense_group:$("#moneyCategory").value||"미분류"});if(error)return toast("지출을 저장하지 못했습니다.");$("#moneyAmount").value="";$("#moneyContent").value="";["#shoppingSearch","#shoppingStatusFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderShopping));["#travelSearch","#travelStatusFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderTrips));["#scheduleSearch","#scheduleDateFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderSchedules));["#moneySearch","#moneyPeriodFilter","#moneyCategoryFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",()=>renderMoney(state.records.filter(x=>x.category==="가계부"&&x.amount!=null))));
document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog")?.close()));document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));document.querySelector("#shareDeviceCalendar")?.addEventListener("click",shareDeviceCalendar);document.querySelector("#openGoogleCalendar")?.addEventListener("click",openGoogleCalendar);
$("#moneyDate").value=iso();toast("지출을 저장했습니다.");await loadAll()}
function renderMoney(all){
  const q=(document.querySelector("#moneySearch")?.value||"").trim().toLowerCase(),period=document.querySelector("#moneyPeriodFilter")?.value||"thisMonth",cat=document.querySelector("#moneyCategoryFilter")?.value||"all",now=new Date();let y=now.getFullYear(),m=now.getMonth()+1;if(period==="lastMonth"){m--;if(m===0){m=12;y--}}const prefix=`${y}-${String(m).padStart(2,"0")}`;
  const list=all.filter(x=>(period==="all"||(x.event_date||"").startsWith(prefix))&&(cat==="all"||(x.expense_group||"미분류")===cat)&&(!q||(x.content||"").toLowerCase().includes(q))).sort((a,b)=>(b.event_date||"").localeCompare(a.event_date||""));
  els.moneyList.innerHTML="";if(!list.length){els.moneyList.innerHTML='<div class="empty">조건에 맞는 지출 내역이 없습니다.</div>';return}
  list.forEach(x=>{const row=document.createElement("div");row.className="money-row";const body=document.createElement("div");body.innerHTML="<strong></strong><div class='meta'></div>";body.querySelector("strong").textContent=x.content;body.querySelector(".meta").textContent=[x.expense_group||"미분류",x.writer,fmtDate(x.event_date)].filter(Boolean).join(" · ");const right=document.createElement("div");const amount=document.createElement("div");amount.className="amount";amount.textContent=money(x.amount);const buttons=document.createElement("div");buttons.className="item-actions";const edit=editButton(()=>editMoney(x));const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("couple_items",x.id,"이 지출 내역을 삭제할까요?");buttons.append(edit,del);right.append(amount,buttons);row.append(body,right);els.moneyList.append(row)})
  if(state.moneyViewMode==="summary")renderMoneySummary(all);
}
function openCategoryManager(mode){state.categoryMode=mode;$("#categoryDialogTitle").textContent=mode==="schedule"?"일정 카테고리 관리":"가계부 카테고리 관리";$("#newCategoryName").value="";renderCategoryManager();$("#categoryDialog").showModal()}
function categoryConfig(){return state.categoryMode==="schedule"?{table:"schedule_categories",items:state.scheduleCategories,recordTable:"schedule_events",field:"category"}:{table:"expense_categories",items:state.expenseCategories,recordTable:"couple_items",field:"expense_group"}}
function renderCategoryManager(){const c=categoryConfig(),box=$("#categoryManageList");box.innerHTML="";c.items.forEach((item,index)=>{const row=document.createElement("div");row.className="category-manage-row";const input=document.createElement("input");input.value=item.name;input.disabled=item.name==="미분류";const order=document.createElement("div");order.className="category-order-buttons";const up=document.createElement("button");up.type="button";up.className="order-button";up.textContent="↑";up.title="위로 이동";up.disabled=index===0;up.onclick=()=>moveCategory(index,-1);const down=document.createElement("button");down.type="button";down.className="order-button";down.textContent="↓";down.title="아래로 이동";down.disabled=index===c.items.length-1;down.onclick=()=>moveCategory(index,1);order.append(up,down);const save=document.createElement("button");save.type="button";save.className="small-button";save.textContent="수정";save.disabled=item.name==="미분류";save.onclick=()=>renameCategory(item,input.value.trim());const del=document.createElement("button");del.type="button";del.className="delete-button";del.textContent="삭제";del.disabled=item.name==="미분류";del.onclick=()=>deleteCategory(item);row.append(input,order,save,del);box.append(row)})}
async function moveCategory(index,direction){const c=categoryConfig(),target=index+direction;if(target<0||target>=c.items.length)return;const ordered=[...c.items];[ordered[index],ordered[target]]=[ordered[target],ordered[index]];const updates=ordered.map((item,i)=>sb.from(c.table).update({sort_order:(i+1)*10}).eq("id",item.id));const results=await Promise.all(updates);if(results.some(r=>r.error))return toast("카테고리 순서를 저장하지 못했습니다.");await loadAll();renderCategoryManager();toast("카테고리 순서를 변경했습니다.")}
async function addCategory(){const name=$("#newCategoryName").value.trim();if(!name)return toast("카테고리 이름을 입력하세요.");const c=categoryConfig();if(c.items.some(x=>x.name===name))return toast("이미 있는 카테고리입니다.");const {error}=await sb.from(c.table).insert({name,sort_order:(c.items.at(-1)?.sort_order||0)+10});if(error)return toast("카테고리를 추가하지 못했습니다.");await loadAll();renderCategoryManager();$("#newCategoryName").value=""}
async function renameCategory(item,newName){if(!newName||newName===item.name)return;if(newName==="미분류")return toast("미분류 이름은 사용할 수 없습니다.");const c=categoryConfig();if(c.items.some(x=>x.name===newName))return toast("이미 있는 카테고리입니다.");let q=sb.from(c.recordTable).update({[c.field]:newName}).eq(c.field,item.name);if(state.categoryMode==="money")q=q.eq("category","가계부");const r=await q;if(r.error)return toast("사용 중인 항목을 수정하지 못했습니다.");const {error}=await sb.from(c.table).update({name:newName}).eq("id",item.id);if(error)return toast("카테고리 이름을 수정하지 못했습니다.");await loadAll();renderCategoryManager();toast("카테고리를 수정했습니다.")}
async function deleteCategory(item){if(!confirm(`'${item.name}' 카테고리를 삭제할까요? 사용 중인 항목은 미분류로 이동합니다.`))return;const c=categoryConfig();let q=sb.from(c.recordTable).update({[c.field]:"미분류"}).eq(c.field,item.name);if(state.categoryMode==="money")q=q.eq("category","가계부");const r=await q;if(r.error)return toast("사용 중인 항목을 이동하지 못했습니다.");const {error}=await sb.from(c.table).delete().eq("id",item.id);if(error)return toast("카테고리를 삭제하지 못했습니다.");await loadAll();renderCategoryManager();toast("카테고리를 삭제했습니다.")}
async function saveSettings(){const payload={id:1,partner_one:$("#partnerOneInput").value.trim()||"진성",partner_two:$("#partnerTwoInput").value.trim()||"성은"};const {error}=await sb.from("couple_settings").upsert(payload);if(error)return toast("설정을 저장하지 못했습니다.");state.settings={...state.settings,...payload};renderAll();toast("설정을 저장했습니다.")}
function openQuickMoney(){switchView("money");const panel=$(".quick-money-panel");panel?.classList.remove("quick-money-focus");requestAnimationFrame(()=>panel?.classList.add("quick-money-focus"));setTimeout(()=>$("#moneyAmount")?.focus(),150)}
function handleLaunchRoute(){const params=new URLSearchParams(location.search);if(params.get("quick")==="expense"||location.hash==="#expense")openQuickMoney()}
$$('.profile-choice').forEach(b=>b.onclick=()=>chooseProfile(b.dataset.profile));$$('.nav-button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$$('[data-go]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();switchView(b.dataset.go)}}));$("#settingsShortcut").onclick=()=>switchView("settings");$("#addShop").onclick=addShopping;$("#clearBought").onclick=async()=>{await sb.from("shopping_items").delete().eq("completed",true);await loadAll()};$("#addTrip").onclick=addTrip;$("#tripStart").onchange=e=>{const end=$("#tripEnd");if(!end.value||end.value<e.target.value)end.value=e.target.value};$("#addSchedule").onclick=addSchedule;$("#calendarViewButton").onclick=()=>showScheduleMode("calendar");$("#listViewButton").onclick=()=>showScheduleMode("list");$("#calendarPrev").onclick=()=>{state.calendarCursor=new Date(state.calendarCursor.getFullYear(),state.calendarCursor.getMonth()-1,1);renderScheduleCalendar()};$("#calendarNext").onclick=()=>{state.calendarCursor=new Date(state.calendarCursor.getFullYear(),state.calendarCursor.getMonth()+1,1);renderScheduleCalendar()};$("#calendarAddSchedule").onclick=()=>openScheduleForm(state.selectedCalendarDate||iso());$("#listAddSchedule").onclick=()=>openScheduleForm(iso());$("#closeScheduleForm").onclick=closeScheduleForm;$("#scheduleStartDate").onchange=e=>{const end=$("#scheduleEndDate");if(!end.value||end.value<e.target.value)end.value=e.target.value};$("#scheduleAllDay").onchange=e=>$("#scheduleTimeRow").hidden=e.target.checked;$("#addMoney").onclick=addMoney;$("#openQuickMoney").onclick=openQuickMoney;$("#moneyListViewButton").onclick=()=>showMoneyMode("list");$("#moneySummaryViewButton").onclick=()=>showMoneyMode("summary");$("#moneySummaryPrev").onclick=()=>setMoneySummaryMonth(-1);$("#moneySummaryNext").onclick=()=>setMoneySummaryMonth(1);$("#moneySummaryMonth").value=state.moneySummaryMonth;$("#moneySummaryMonth").onchange=e=>{state.moneySummaryMonth=e.target.value||iso().slice(0,7);renderMoneySummary(state.records.filter(x=>x.category==="가계부"&&x.amount!=null))};$("#openScheduleCategories").onclick=()=>openCategoryManager("schedule");$("#openMoneyCategories").onclick=()=>openCategoryManager("money");$("#addCategoryButton").onclick=addCategory;$("#saveEditButton").onclick=saveEditedItem;$("#saveSettings").onclick=saveSettings;$("#changeProfile").onclick=()=>{localStorage.removeItem("couple_profile");state.profile=null;els.app.hidden=true;els.profileScreen.hidden=false};
["#shoppingSearch","#shoppingStatusFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderShopping));["#travelSearch","#travelStatusFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderTrips));["#scheduleSearch","#scheduleDateFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",renderSchedules));["#moneySearch","#moneyPeriodFilter","#moneyCategoryFilter"].forEach(id=>document.querySelector(id)?.addEventListener("input",()=>renderMoney(state.records.filter(x=>x.category==="가계부"&&x.amount!=null))));
document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog")?.close()));document.querySelectorAll("dialog").forEach(d=>d.addEventListener("click",e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));document.querySelector("#shareDeviceCalendar")?.addEventListener("click",shareDeviceCalendar);document.querySelector("#openGoogleCalendar")?.addEventListener("click",openGoogleCalendar);
$("#moneyDate").value=iso();els.today.textContent=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(new Date());if(state.profile)openApp();
sb.channel("couple-v7-live").on("postgres_changes",{event:"*",schema:"public",table:"shopping_items"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"travel_plans"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"couple_items"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"couple_settings"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"schedule_events"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"schedule_categories"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"expense_categories"},loadAll).subscribe();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));

window.addEventListener("load",()=>setTimeout(()=>document.querySelector("#appSplash")?.classList.add("hide"),500));
setTimeout(()=>document.querySelector("#appSplash")?.classList.add("hide"),1800);
