const cfg=window.APP_CONFIG;
const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={profile:localStorage.getItem("couple_profile"),settings:{id:1,partner_one:"진성",partner_two:"성은"},shopping:[],trips:[],records:[],schedules:[],scheduleCategories:[],expenseCategories:[],scheduleFilter:"전체",categoryMode:null};
const els={profileScreen:$("#profileScreen"),app:$("#app"),toast:$("#toast"),oneName:$("#profileOneName"),twoName:$("#profileTwoName"),today:$("#todayText"),pageTitle:$("#pageTitle"),welcome:$("#welcomeName"),shoppingCount:$("#shoppingCount"),tripCount:$("#tripCount"),scheduleCount:$("#scheduleCount"),homeExpenseTotal:$("#homeExpenseTotal"),homeSchedules:$("#homeSchedules"),homeTrips:$("#homeTrips"),shoppingList:$("#shoppingList"),tripList:$("#tripList"),scheduleList:$("#scheduleList"),scheduleFilters:$("#scheduleFilters"),currentProfile:$("#currentProfileText"),moneyWriter:$("#moneyWriter"),moneyList:$("#moneyList"),monthExpenseTotal:$("#monthExpenseTotal"),monthExpenseCount:$("#monthExpenseCount")};
function toast(msg){els.toast.textContent=msg;els.toast.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>els.toast.hidden=true,2500)}
function iso(d=new Date()){return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function fmtDate(v){return v?new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"short",day:"numeric"}).format(new Date(v+"T00:00:00")):""}
function money(v){return `${Number(v||0).toLocaleString("ko-KR")}원`}
function currentName(){return state.profile==="one"?state.settings.partner_one:state.settings.partner_two}
function escapeICS(v=""){return String(v).replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function localCalendarKey(item){return `calendar_saved_${item.source}_${item.id}`}
function isCalendarSaved(item){return localStorage.getItem(localCalendarKey(item))==="1"}
function ymdCompact(v){return (v||iso()).replaceAll("-","")}
function dtCompact(date,time){return `${ymdCompact(date)}T${(time||"09:00").replace(":","")}00`}

async function loadAll(){
  const qs=await Promise.all([
    sb.from("couple_settings").select("*").eq("id",1).maybeSingle(),sb.from("shopping_items").select("*").order("created_at",{ascending:false}),sb.from("travel_plans").select("*").order("start_date",{ascending:true}),sb.from("couple_items").select("*").order("created_at",{ascending:false}),sb.from("schedule_events").select("*").order("start_date",{ascending:true}),sb.from("schedule_categories").select("*").order("sort_order"),sb.from("expense_categories").select("*").order("sort_order")
  ]);
  if(qs[0].data)state.settings={...state.settings,...qs[0].data};state.shopping=qs[1].data||[];state.trips=qs[2].data||[];state.records=qs[3].data||[];state.schedules=qs[4].data||[];state.scheduleCategories=qs[5].data||[];state.expenseCategories=qs[6].data||[];
  if(qs.some(q=>q.error))toast("일부 데이터를 불러오지 못했습니다. setup_v7.sql 실행 여부를 확인하세요.");renderAll();
}
function openApp(){els.profileScreen.hidden=true;els.app.hidden=false;loadAll().then(handleLaunchRoute)}
function chooseProfile(profile){state.profile=profile;localStorage.setItem("couple_profile",profile);openApp()}
function switchView(view){$$('.view').forEach(v=>v.classList.remove('active'));$("#"+view+"View").classList.add("active");$$('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));els.pageTitle.textContent={home:"홈",shopping:"장보기",travel:"여행",schedule:"일정",money:"가계부",settings:"설정"}[view];if(view==="money")setTimeout(()=>$("#moneyAmount")?.focus(),120)}
function unifiedSchedules(){
  const normal=state.schedules.map(x=>({...x,source:"schedule",sourceLabel:"일정"}));
  const trips=state.trips.filter(x=>x.start_date).map(x=>({id:x.id,title:`✈ ${x.title}`,start_date:x.start_date,end_date:x.end_date||x.start_date,all_day:true,start_time:null,end_time:null,category:"여행",location:null,memo:x.memo,writer:x.writer,source:"travel",sourceLabel:"여행"}));
  return [...normal,...trips].sort((a,b)=>(a.start_date||"").localeCompare(b.start_date||""));
}
function renderAll(){
  els.oneName.textContent=state.settings.partner_one;els.twoName.textContent=state.settings.partner_two;els.welcome.textContent=`${currentName()}님, 안녕하세요`;els.currentProfile.textContent=`이 기기 사용자: ${currentName()}`;$("#partnerOneInput").value=state.settings.partner_one;$("#partnerTwoInput").value=state.settings.partner_two;
  els.moneyWriter.innerHTML="";[state.settings.partner_one,state.settings.partner_two].forEach(n=>els.moneyWriter.add(new Option(n,n)));
  fillCategorySelects();
  const now=new Date(), monthlyExpenses=state.records.filter(x=>{if(x.category!=="가계부"||x.amount==null)return false;const d=x.event_date?new Date(x.event_date+"T00:00:00"):new Date(x.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});const monthlyTotal=monthlyExpenses.reduce((sum,x)=>sum+Number(x.amount||0),0);const all=unifiedSchedules();
  els.shoppingCount.textContent=state.shopping.filter(x=>!x.completed).length;els.tripCount.textContent=state.trips.filter(x=>!x.end_date||x.end_date>=iso()).length;els.scheduleCount.textContent=all.filter(x=>(x.end_date||x.start_date)>=iso()).length;els.homeExpenseTotal.textContent=money(monthlyTotal);els.monthExpenseTotal.textContent=money(monthlyTotal);els.monthExpenseCount.textContent=`${monthlyExpenses.length}건`;
  renderMini(els.homeSchedules,all.filter(x=>(x.end_date||x.start_date)>=iso()).slice(0,4).map(x=>({title:x.title,meta:`${fmtDate(x.start_date)} · ${x.category||"미분류"}`})),"다가오는 일정이 없습니다.");renderMini(els.homeTrips,state.trips.filter(x=>!x.end_date||x.end_date>=iso()).slice(0,3).map(x=>({title:x.title,meta:[fmtDate(x.start_date),fmtDate(x.end_date)].filter(Boolean).join(" ~ ")})),"예정된 여행이 없습니다.");renderShopping();renderTrips();renderSchedules();renderMoney(monthlyExpenses);
}
function fillCategorySelects(){const sc=$("#scheduleCategory"),mc=$("#moneyCategory");const sv=sc.value,mv=mc.value;sc.innerHTML="";mc.innerHTML="";(state.scheduleCategories.length?state.scheduleCategories:[{name:"미분류"}]).forEach(c=>sc.add(new Option(c.name,c.name)));(state.expenseCategories.length?state.expenseCategories:[{name:"기타"}]).forEach(c=>mc.add(new Option(c.name,c.name)));if([...sc.options].some(o=>o.value===sv))sc.value=sv;if([...mc.options].some(o=>o.value===mv))mc.value=mv}
function renderMini(container,list,emptyText){container.innerHTML="";if(!list.length){container.innerHTML=`<div class="empty">${emptyText}</div>`;return}list.forEach(x=>{const row=document.createElement("div");row.className="list-item";row.innerHTML="<div></div><div><strong></strong><div class='meta'></div></div><div></div>";row.querySelector("strong").textContent=x.title;row.querySelector(".meta").textContent=x.meta||"";container.append(row)})}
async function addShopping(){const item=$("#shopItem").value.trim();if(!item)return toast("살 물건을 입력하세요.");const {error}=await sb.from("shopping_items").insert({item_name:item,quantity:$("#shopQty").value.trim()||null,store:$("#shopStore").value||null,completed:false,writer:currentName()});if(error)return toast("추가하지 못했습니다.");$("#shopItem").value="";$("#shopQty").value="";await loadAll()}
async function toggleShopping(item){await sb.from("shopping_items").update({completed:!item.completed}).eq("id",item.id);await loadAll()}
async function removeRow(table,id,message="삭제할까요?"){if(!confirm(message))return;await sb.from(table).delete().eq("id",id);await loadAll()}
function renderShopping(){els.shoppingList.innerHTML="";if(!state.shopping.length){els.shoppingList.innerHTML='<div class="empty">쇼핑리스트가 비어 있습니다.</div>';return}state.shopping.forEach(x=>{const row=document.createElement("div");row.className=`list-item ${x.completed?"done":""}`;const check=document.createElement("button");check.className="check-button";check.textContent=x.completed?"✓":"";check.onclick=()=>toggleShopping(x);const body=document.createElement("div");body.innerHTML="<strong></strong><div class='meta'></div>";body.querySelector("strong").textContent=x.item_name;body.querySelector(".meta").textContent=[x.quantity,x.store,x.writer].filter(Boolean).join(" · ");const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("shopping_items",x.id);row.append(check,body,del);els.shoppingList.append(row)})}
async function addTrip(){const title=$("#tripTitle").value.trim();if(!title)return toast("여행 이름이나 목적지를 입력하세요.");const {error}=await sb.from("travel_plans").insert({title,start_date:$("#tripStart").value||null,end_date:$("#tripEnd").value||null,memo:$("#tripMemo").value.trim()||null,writer:currentName()});if(error)return toast("여행 계획을 추가하지 못했습니다.");$("#tripTitle").value="";$("#tripStart").value="";$("#tripEnd").value="";$("#tripMemo").value="";await loadAll()}
function renderTrips(){els.tripList.innerHTML="";if(!state.trips.length){els.tripList.innerHTML='<div class="empty">등록된 여행 계획이 없습니다.</div>';return}state.trips.forEach(x=>{const card=document.createElement("article");card.className="trip-card";const title=document.createElement("strong");title.textContent=x.title;const meta=document.createElement("div");meta.className="meta";meta.textContent=[fmtDate(x.start_date),fmtDate(x.end_date),x.writer].filter(Boolean).join(" ~ ");const memo=document.createElement("p");memo.textContent=x.memo||"메모 없음";const actions=document.createElement("div");actions.className="card-actions";const cal=calendarButton({...x,source:"travel",category:"여행",all_day:true});const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("travel_plans",x.id,"여행 계획을 삭제할까요?");actions.append(cal,del);card.append(title,meta,memo,actions);els.tripList.append(card)})}
async function addSchedule(){const title=$("#scheduleTitle").value.trim(),start=$("#scheduleStartDate").value,end=$("#scheduleEndDate").value||start;if(!title)return toast("일정 제목을 입력하세요.");if(!start)return toast("시작 날짜를 선택하세요.");if(end<start)return toast("종료 날짜를 확인하세요.");const all=$("#scheduleAllDay").checked;const {error}=await sb.from("schedule_events").insert({title,start_date:start,end_date:end,all_day:all,start_time:all?null:$("#scheduleStartTime").value||null,end_time:all?null:$("#scheduleEndTime").value||null,category:$("#scheduleCategory").value||"미분류",location:$("#scheduleLocation").value.trim()||null,memo:$("#scheduleMemo").value.trim()||null,writer:currentName()});if(error)return toast("일정을 저장하지 못했습니다.");["#scheduleTitle","#scheduleStartDate","#scheduleEndDate","#scheduleStartTime","#scheduleEndTime","#scheduleLocation","#scheduleMemo"].forEach(s=>$(s).value="");$("#scheduleAllDay").checked=true;$("#scheduleTimeRow").hidden=true;await loadAll();toast("일정을 저장했습니다.")}
function renderSchedules(){const all=unifiedSchedules();els.scheduleFilters.innerHTML="";["전체","여행",...state.scheduleCategories.map(c=>c.name).filter(n=>n!=="여행")].filter((v,i,a)=>a.indexOf(v)===i).forEach(name=>{const b=document.createElement("button");b.className=`chip ${state.scheduleFilter===name?"active":""}`;b.textContent=name;b.onclick=()=>{state.scheduleFilter=name;renderSchedules()};els.scheduleFilters.append(b)});const list=state.scheduleFilter==="전체"?all:all.filter(x=>(x.category||"미분류")===state.scheduleFilter);els.scheduleList.innerHTML="";if(!list.length){els.scheduleList.innerHTML='<div class="empty">표시할 일정이 없습니다.</div>';return}list.forEach(x=>{const card=document.createElement("article");card.className=`schedule-card ${x.source==="travel"?"travel-linked":""}`;const top=document.createElement("div");top.className="schedule-card-top";const title=document.createElement("strong");title.textContent=x.title;const badge=document.createElement("span");badge.className="category-badge";badge.textContent=x.category||"미분류";top.append(title,badge);const meta=document.createElement("div");meta.className="meta";meta.textContent=[dateRangeText(x),x.location,x.writer].filter(Boolean).join(" · ");const memo=document.createElement("p");memo.textContent=x.memo||"";const actions=document.createElement("div");actions.className="card-actions";actions.append(calendarButton(x));if(x.source==="schedule"){const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("schedule_events",x.id,"이 일정을 삭제할까요?");actions.append(del)}else{const hint=document.createElement("small");hint.textContent="여행 메뉴와 자동 연결됨";actions.append(hint)}card.append(top,meta,memo,actions);els.scheduleList.append(card)})}
function dateRangeText(x){const d=x.start_date===x.end_date||!x.end_date?fmtDate(x.start_date):`${fmtDate(x.start_date)} ~ ${fmtDate(x.end_date)}`;return x.all_day!==false?d:`${d} ${x.start_time||""}${x.end_time?`~${x.end_time}`:""}`}
function calendarButton(item){const b=document.createElement("button");b.className=isCalendarSaved(item)?"calendar-button saved":"calendar-button";b.textContent=isCalendarSaved(item)?"✓ 저장 완료":"📅 휴대폰 캘린더에 추가";b.onclick=()=>addToDeviceCalendar(item,b);return b}
function addToDeviceCalendar(item,button){if(isCalendarSaved(item)&&!confirm("이미 이 휴대폰에서 추가한 일정입니다. 다시 추가하면 중복될 수 있습니다. 다시 추가할까요?"))return;const start=item.start_date||iso(),end=item.end_date||start;let dates;if(item.all_day!==false){const next=new Date(end+"T00:00:00");next.setDate(next.getDate()+1);dates=`${ymdCompact(start)}/${ymdCompact(iso(next))}`}else{const startTime=item.start_time||"09:00",endTime=item.end_time||startTime;dates=`${dtCompact(start,startTime)}/${dtCompact(end,endTime)}`}
  const params=new URLSearchParams({action:"TEMPLATE",text:item.title||"일정",dates,details:item.memo||"",location:item.location||"",ctz:"Asia/Seoul"});const url=`https://calendar.google.com/calendar/render?${params.toString()}`;const opened=window.open(url,"_blank");if(!opened)window.location.href=url;localStorage.setItem(localCalendarKey(item),"1");button.textContent="✓ 저장 완료";button.classList.add("saved");toast("Google 캘린더에서 저장을 눌러주세요.")}

async function addMoney(){const amount=Number($("#moneyAmount").value),content=$("#moneyContent").value.trim();if(!amount||amount<=0)return toast("금액을 입력하세요.");if(!content)return toast("사용한 곳이나 내용을 입력하세요.");const {error}=await sb.from("couple_items").insert({content,category:"가계부",writer:els.moneyWriter.value,completed:false,event_date:$("#moneyDate").value||iso(),amount,expense_group:$("#moneyCategory").value||"미분류"});if(error)return toast("지출을 저장하지 못했습니다.");$("#moneyAmount").value="";$("#moneyContent").value="";$("#moneyDate").value=iso();toast("지출을 저장했습니다.");await loadAll()}
function renderMoney(list){els.moneyList.innerHTML="";if(!list.length){els.moneyList.innerHTML='<div class="empty">이번 달 지출 내역이 없습니다.</div>';return}list.sort((a,b)=>(b.event_date||"").localeCompare(a.event_date||""));list.forEach(x=>{const row=document.createElement("div");row.className="money-row";const body=document.createElement("div");body.innerHTML="<strong></strong><div class='meta'></div>";body.querySelector("strong").textContent=x.content;body.querySelector(".meta").textContent=[x.expense_group||"미분류",x.writer,fmtDate(x.event_date)].filter(Boolean).join(" · ");const right=document.createElement("div");const amount=document.createElement("div");amount.className="amount";amount.textContent=money(x.amount);const del=document.createElement("button");del.className="delete-button";del.textContent="삭제";del.onclick=()=>removeRow("couple_items",x.id,"이 지출 내역을 삭제할까요?");right.append(amount,del);row.append(body,right);els.moneyList.append(row)})}
function openCategoryManager(mode){state.categoryMode=mode;$("#categoryDialogTitle").textContent=mode==="schedule"?"일정 카테고리 관리":"가계부 카테고리 관리";$("#newCategoryName").value="";renderCategoryManager();$("#categoryDialog").showModal()}
function categoryConfig(){return state.categoryMode==="schedule"?{table:"schedule_categories",items:state.scheduleCategories,recordTable:"schedule_events",field:"category"}:{table:"expense_categories",items:state.expenseCategories,recordTable:"couple_items",field:"expense_group"}}
function renderCategoryManager(){const c=categoryConfig(),box=$("#categoryManageList");box.innerHTML="";c.items.forEach(item=>{const row=document.createElement("div");row.className="category-manage-row";const input=document.createElement("input");input.value=item.name;input.disabled=item.name==="미분류";const save=document.createElement("button");save.type="button";save.className="small-button";save.textContent="수정";save.disabled=item.name==="미분류";save.onclick=()=>renameCategory(item,input.value.trim());const del=document.createElement("button");del.type="button";del.className="delete-button";del.textContent="삭제";del.disabled=item.name==="미분류";del.onclick=()=>deleteCategory(item);row.append(input,save,del);box.append(row)})}
async function addCategory(){const name=$("#newCategoryName").value.trim();if(!name)return toast("카테고리 이름을 입력하세요.");const c=categoryConfig();if(c.items.some(x=>x.name===name))return toast("이미 있는 카테고리입니다.");const {error}=await sb.from(c.table).insert({name,sort_order:(c.items.at(-1)?.sort_order||0)+10});if(error)return toast("카테고리를 추가하지 못했습니다.");await loadAll();renderCategoryManager();$("#newCategoryName").value=""}
async function renameCategory(item,newName){if(!newName||newName===item.name)return;if(newName==="미분류")return toast("미분류 이름은 사용할 수 없습니다.");const c=categoryConfig();if(c.items.some(x=>x.name===newName))return toast("이미 있는 카테고리입니다.");let q=sb.from(c.recordTable).update({[c.field]:newName}).eq(c.field,item.name);if(state.categoryMode==="money")q=q.eq("category","가계부");const r=await q;if(r.error)return toast("사용 중인 항목을 수정하지 못했습니다.");const {error}=await sb.from(c.table).update({name:newName}).eq("id",item.id);if(error)return toast("카테고리 이름을 수정하지 못했습니다.");await loadAll();renderCategoryManager();toast("카테고리를 수정했습니다.")}
async function deleteCategory(item){if(!confirm(`'${item.name}' 카테고리를 삭제할까요? 사용 중인 항목은 미분류로 이동합니다.`))return;const c=categoryConfig();let q=sb.from(c.recordTable).update({[c.field]:"미분류"}).eq(c.field,item.name);if(state.categoryMode==="money")q=q.eq("category","가계부");const r=await q;if(r.error)return toast("사용 중인 항목을 이동하지 못했습니다.");const {error}=await sb.from(c.table).delete().eq("id",item.id);if(error)return toast("카테고리를 삭제하지 못했습니다.");await loadAll();renderCategoryManager();toast("카테고리를 삭제했습니다.")}
async function saveSettings(){const payload={id:1,partner_one:$("#partnerOneInput").value.trim()||"진성",partner_two:$("#partnerTwoInput").value.trim()||"성은"};const {error}=await sb.from("couple_settings").upsert(payload);if(error)return toast("설정을 저장하지 못했습니다.");state.settings={...state.settings,...payload};renderAll();toast("설정을 저장했습니다.")}
function openQuickMoney(){switchView("money");const panel=$(".quick-money-panel");panel?.classList.remove("quick-money-focus");requestAnimationFrame(()=>panel?.classList.add("quick-money-focus"));setTimeout(()=>$("#moneyAmount")?.focus(),150)}
function handleLaunchRoute(){const params=new URLSearchParams(location.search);if(params.get("quick")==="expense"||location.hash==="#expense")openQuickMoney()}
$$('.profile-choice').forEach(b=>b.onclick=()=>chooseProfile(b.dataset.profile));$$('.nav-button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$("#settingsShortcut").onclick=()=>switchView("settings");$("#addShop").onclick=addShopping;$("#clearBought").onclick=async()=>{await sb.from("shopping_items").delete().eq("completed",true);await loadAll()};$("#addTrip").onclick=addTrip;$("#addSchedule").onclick=addSchedule;$("#scheduleStartDate").onchange=e=>{const end=$("#scheduleEndDate");if(!end.value||end.value<e.target.value)end.value=e.target.value};$("#scheduleAllDay").onchange=e=>$("#scheduleTimeRow").hidden=e.target.checked;$("#addMoney").onclick=addMoney;$("#openQuickMoney").onclick=openQuickMoney;$("#openScheduleCategories").onclick=()=>openCategoryManager("schedule");$("#openMoneyCategories").onclick=()=>openCategoryManager("money");$("#addCategoryButton").onclick=addCategory;$("#saveSettings").onclick=saveSettings;$("#changeProfile").onclick=()=>{localStorage.removeItem("couple_profile");state.profile=null;els.app.hidden=true;els.profileScreen.hidden=false};
$("#moneyDate").value=iso();els.today.textContent=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"long"}).format(new Date());if(state.profile)openApp();
sb.channel("couple-v7-live").on("postgres_changes",{event:"*",schema:"public",table:"shopping_items"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"travel_plans"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"couple_items"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"couple_settings"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"schedule_events"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"schedule_categories"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"expense_categories"},loadAll).subscribe();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));
